social:
    - identifier: github
      name: GitHub
      url: https://github.com/Footman56
      params:
        icon: github

    - identifier: mail
      name: Email
      url: "mailto:17633150922@163.com"
      params:
        icon: mail
